### ISSUE TITLE
Calendar date adding wrappingComponents implementation is incorrect

### ISSUE THREAD

**Issue by tyiu** [skiptools/skip-foundation#17]
TestCalendar `test_addingDates_issue182` fails for me for Android:
https://github.com/skiptools/skip-foundation/commit/5cce43c6f1c8b0c39db7d96c8d3a3057b1247f54#diff-49cc810690d65bd6cbfa02f61ddd13fb61fdbda36d5cad1464219999e7e80624R263

`java.lang.AssertionError: 29 != 30`

**Comment by marcprux** [comment]
Hmm. It is passing for me, and it is passing in CI (see https://github.com/skiptools/skip-foundation/actions/runs/10701402474).

When it fails for you, are you running the test case locally, or against an Android device/emulator? Out of curiosity, what is your time zone set to? It shouldn't matter (since we set up with `calendar.timeZone = TimeZone(identifier: "UTC")`), but it could be a factor…

**Comment by tyiu** [comment]
> Hmm. It is passing for me, and it is passing in CI (see https://github.com/skiptools/skip-foundation/actions/runs/10701402474).
> 
> 
> 
> When it fails for you, are you running the test case locally, or against an Android device/emulator? Out of curiosity, what is your time zone set to? It shouldn't matter (since we set up with `calendar.timeZone = TimeZone(identifier: "UTC")`), but it could be a factor…

I'm running the test locally which is going through Robolectric. My time zone is UTC+3 as I'm temporarily in Europe. Normally I'm in the US.

**Comment by marcprux** [comment]
Yeah, I'm seeing it fail as well if I run `TZ=GMT+3 skip test`. Looking into it…

**Comment by marcprux** [comment]
I believe this should be fixed in release 1.1.6 by https://github.com/skiptools/skip-foundation/pull/23. I'll close this issue, but if it still affects you, please re-open.
